name: Check with Python-Black

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  - name: Run Black Check
    uses: piotrpawlaczek/python-blacken@release/stable
    with:
      sanity-check: 'safe'
