- name: Python Blacken
  # You may pin to the exact commit or the version.
  # uses: piotrpawlaczek/python-blacken@3300482ee29b6fe01c4c67e1e579a26b3ac17bf5
  uses: piotrpawlaczek/python-blacken@v22.3.0
  with:
    # File or directory to run black on.
    path: # optional, default is .
    # The number of characters allowed per line.
    line-length: # optional, default is 88
    # Sanity check [fast|safe]
    sanity-check: # optional, default is safe
    # Only check the files instead of modify them [yes|no] 
    only-check: # optional, default is yes
