name: Check with Python-Black

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run Black Check
        uses: piotrpawlaczek/python-blacken@release/stable
        with:
          sanity-check: 'safe'
          path: '.'
